"""Push engineered Karachi AQI features to Hopsworks feature store."""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv


FEATURES_PATH = Path("data/processed/karachi_features.csv")


def load_features(path: Path) -> pd.DataFrame:
    """Load engineered features generated by build_features script."""
    if not path.exists():
        raise FileNotFoundError(
            f"Features file not found at {path}. Run src/features/build_features.py first."
        )

    df = pd.read_csv(path, parse_dates=["timestamp"])
    if df.empty:
        raise ValueError("Features dataframe is empty. Nothing to upload.")

    return df


def push_features_to_store(df: pd.DataFrame) -> None:
    """Upload features dataframe to Hopsworks feature group."""
    load_dotenv()

    api_key = os.getenv("HOPSWORKS_API_KEY")
    project_name = os.getenv("HOPSWORKS_PROJECT", "pearls_aqi_predictor")
    hopsworks_host = os.getenv("HOPSWORKS_HOST", "run.hopsworks.ai")
    hopsworks_port = int(os.getenv("HOPSWORKS_PORT", "443"))
    feature_group_name = os.getenv("HOPSWORKS_FEATURE_GROUP", "karachi_aqi_features")
    feature_group_version = int(os.getenv("HOPSWORKS_FEATURE_GROUP_VERSION", "1"))

    if not api_key:
        raise ValueError("Missing HOPSWORKS_API_KEY in .env for feature store upload.")

    try:
        import hopsworks
    except ImportError as exc:
        raise ImportError(
            "hopsworks package is not installed. Add it to requirements and install."
        ) from exc

    project = hopsworks.login(
        project=project_name,
        host=hopsworks_host,
        port=hopsworks_port,
        api_key_value=api_key,
    )
    feature_store = project.get_feature_store()

    if "id" not in df.columns:
        df = df.copy()
        df["id"] = range(1, len(df) + 1)

    feature_group = feature_store.get_or_create_feature_group(
        name=feature_group_name,
        version=feature_group_version,
        description="Karachi AQI engineered features for forecasting",
        primary_key=["id"],
        event_time="timestamp",
        online_enabled=False,
    )

    feature_group.insert(df, write_options={"wait_for_job": True})
    print(
        "Uploaded features to Hopsworks: "
        f"{feature_group_name} v{feature_group_version} ({len(df)} rows)"
    )


def main() -> None:
    """Run upload workflow from local features file to Hopsworks."""
    df = load_features(FEATURES_PATH)
    push_features_to_store(df)


if __name__ == "__main__":
    main()
