"""Streamlit dashboard for Karachi Daily Average AQI forecast."""

from __future__ import annotations

import os
from typing import Any

import pandas as pd
import requests
import streamlit as st


st.set_page_config(page_title="Karachi Daily AQI Forecast", page_icon="AQI", layout="wide")

API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")


def aqi_category(aqi: int) -> tuple[str, str]:
    """Map AQI numeric value to category and color."""
    if aqi <= 50:
        return "Good", "#2e7d32"
    if aqi <= 100:
        return "Moderate", "#ef6c00"
    if aqi <= 150:
        return "Unhealthy (Sensitive)", "#f9a825"
    if aqi <= 200:
        return "Unhealthy", "#d32f2f"
    if aqi <= 300:
        return "Very Unhealthy", "#6a1b9a"
    return "Hazardous", "#4e342e"


def get_json(endpoint: str) -> dict[str, Any]:
    """Fetch JSON from FastAPI backend."""
    response = requests.get(f"{API_BASE_URL}{endpoint}", timeout=30)
    response.raise_for_status()
    return response.json()


def render_header() -> None:
    """Render dashboard heading and context."""
    st.title("Karachi Daily Average AQI Forecast")
    st.caption("Three-day forecast generated by local ensemble model service")
    st.markdown(
        "This dashboard shows predicted **Daily Average PM2.5** and corresponding **AQI** "
        "for Day 1, Day 2, and Day 3."
    )


def render_day1_warning(day1_aqi: int) -> None:
    """Render warning banner when Day 1 AQI exceeds safety threshold."""
    if day1_aqi >= 150:
        st.error(
            f"Day 1 AQI alert: forecasted AQI is {day1_aqi} (>= 150). "
            "Air quality is unhealthy. Recommend limiting outdoor exposure."
        )
    elif day1_aqi >= 100:
        st.warning(
            f"Day 1 AQI caution: forecasted AQI is {day1_aqi}. "
            "Sensitive groups should reduce prolonged outdoor activity."
        )
    else:
        st.success(f"Day 1 AQI is {day1_aqi}. Conditions are within safer range.")


def render_forecast_cards(payload: dict[str, Any]) -> None:
    """Render forecast cards for Day 1/Day 2/Day 3 daily averages."""
    cols = st.columns(3)
    labels = [
        ("day_1", "Day 1 (+24h)"),
        ("day_2", "Day 2 (+48h)"),
        ("day_3", "Day 3 (+72h)"),
    ]

    for col, (day_key, title) in zip(cols, labels):
        pm25_value = float(payload["daily_avg_pm2_5_forecast"][day_key])
        aqi_value = int(payload["daily_avg_aqi_forecast"][day_key])
        band, color = aqi_category(aqi_value)
        with col:
            st.metric(label=title, value=f"{pm25_value:.1f} ug/m^3", delta=f"AQI {aqi_value}")
            st.markdown(
                f"<div style='color:{color};font-weight:600;margin-top:-0.4rem'>{band}</div>",
                unsafe_allow_html=True,
            )


def render_metadata(payload: dict[str, Any]) -> None:
    """Render model provenance and inference context."""
    st.markdown("### Inference Context")
    st.write(f"City: `{payload['city']}`")
    st.write(f"Source timestamp: `{payload['generated_from_timestamp']}`")
    st.write(f"Model source: `{payload['model_source']}`")
    st.write(f"Prediction unit: `{payload['prediction_unit']}`")


def render_trajectory_chart(payload: dict[str, Any]) -> None:
    """Render 3-day forecast trajectory line chart."""
    chart_df = pd.DataFrame(
        {
            "Day": ["Day 1", "Day 2", "Day 3"],
            "Daily Average PM2.5": [
                float(payload["daily_avg_pm2_5_forecast"]["day_1"]),
                float(payload["daily_avg_pm2_5_forecast"]["day_2"]),
                float(payload["daily_avg_pm2_5_forecast"]["day_3"]),
            ],
            "AQI": [
                int(payload["daily_avg_aqi_forecast"]["day_1"]),
                int(payload["daily_avg_aqi_forecast"]["day_2"]),
                int(payload["daily_avg_aqi_forecast"]["day_3"]),
            ],
        }
    )
    st.markdown("### 3-Day Forecast Trajectory")
    st.line_chart(chart_df.set_index("Day")[["Daily Average PM2.5"]], height=260)
    st.dataframe(chart_df, use_container_width=True)


def render_feature_importance(payload: dict[str, Any]) -> None:
    """Render top feature drivers for Day-1 AQI prediction."""
    st.markdown("### What is driving today's AQI?")
    importance = payload.get("feature_importance", {})
    if not isinstance(importance, dict) or not importance:
        st.info("Feature importance is not available for this model output.")
        return

    imp_df = pd.DataFrame(
        {
            "feature": list(importance.keys()),
            "importance": [float(v) for v in importance.values()],
        }
    )
    imp_df = imp_df.sort_values("importance", ascending=True)
    st.bar_chart(imp_df.set_index("feature")["importance"], height=260, horizontal=True)
    st.caption("Importance is normalized contribution (%) for the Day-1 prediction.")


def main() -> None:
    """Dashboard entry point."""
    render_header()

    with st.sidebar:
        st.markdown("### Backend")
        st.code(API_BASE_URL)
        st.caption("Set API_BASE_URL env var if API is running on another host/port.")

    try:
        prediction = get_json("/predict/karachi")
    except Exception as exc:
        st.error(f"Failed to fetch forecast data from backend: {exc}")
        st.stop()

    render_day1_warning(int(prediction["daily_avg_aqi_forecast"]["day_1"]))
    render_forecast_cards(prediction)
    render_trajectory_chart(prediction)
    render_feature_importance(prediction)
    render_metadata(prediction)


if __name__ == "__main__":
    main()
